spring:
  application:
    name: college-website

  profiles:
    active: dev

  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
  error:
    include-message: never
    include-stacktrace: never

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}
    refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}

  admin:
    username: ${ADMIN_USERNAME:superadmin}
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}

  contact:
    my-email: princibun@bdu.ac.in

logging:
  level:
    root: INFO
    com.Lider.college_website: DEBUG
    org.springframework.security: WARN
    org.hibernate.SQL: DEBUG
